spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: admin
    url: jdbc:mysql://localhost:3306/dcbapp
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'
welcome:
  message: Welcome To Daffodil!!
server:
  port: '8082'
